language: perl
perl:
  - "5.19"
  - "5.18.1_thr"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8.9"
  - "5.8.3"
  - "5.8.1"
before_install:
  - "source devel.travis/travis-perlbrew"
  - "perlbrew install-cpanm -f"
  - "perl -V"
install:
  - cpanm Exporter::Tiny Import::Into Module::Runtime Try::Tiny
  - cpanm Test::More Test::Fatal Test::LongString Test::Deep Test::Warnings
  # Test::API test suite craps out on Perl 5.8.x
  - cpanm -n Test::API
script:
  - "HARNESS_IS_VERBOSE=1 prove -Ilib t"
matrix:
  include:
    - perl: "5.6.2"
      install:
        - "perl -Idevel.travis -MCPAN -e'install q(Test::More)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Exporter::Tiny)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Import::Into)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Module::Runtime)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Try::Tiny)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Test::Fatal)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Test::LongString)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Test::Deep)'"
        - "perl -Idevel.travis -MCPAN -e'install q(Test::Warnings)'"
      script:
        - "HARNESS_IS_VERBOSE=1 perl /home/travis/perl5/perlbrew/perls/5.6.2/bin/prove -r -Ilib -Iinc t"
#notifications:
#  irc:
#    channels:
#      - "irc.perl.org#moops"
#    on_success: change
